### ISSUE TITLE
"Github not found" when running the container

### ISSUE THREAD

**Issue by leomat** [hydazz/docker-akaunting#2]
Hi ! 

I'm trying to run this container on a RPI4, but when I running the command below: 
`docker run -d \
  --name=akaunting \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Australia/Melbourne \
  -p 443:443 \
  -p 80:80 \
  -v <path to appdata>:/config \
  --restart unless-stopped \
  vcxpz/akaunting` 

I'm getting the following errors in my logs: 

![image](https://user-images.githubusercontent.com/227758/117284124-cd592200-ae66-11eb-929d-f2c086bdfff8.png)

What am I doing wrong? 

Thanks

**Comment by hydazz** [comment]
Try to add `--dns=1.1.1.1` somewhere before `vcxpz/akaunting`, you can replace `1.1.1.1` with your own DNS server or just use Cloudflare.
let me know how you go!

**Comment by leomat** [comment]
Thanks for the fast answer ! 

Unfortunately, it doesn't work. I get the exact same message. I tried different DNS (even mine) but no effect.

**Comment by hydazz** [comment]
What is the output of `cat /etc/docker/daemon.json`? (on the rpi host)

**Comment by leomat** [comment]
I have this: 
`
{
  "data-root": "/var/lib/docker"
}

`

**Comment by hydazz** [comment]
try editing the /etc/docker/daemon.json to this:

```json
{
     "data-root": "/var/lib/docker",
     "dns": [
          "1.1.1.1"
     ]
}
```
this will make all containers and docker use the specified DNS server, my mac also had this same issue and adding that to the daemon config fixed it for me. be sure to restart docker after editing.

**Comment by leomat** [comment]
Unfortunately, the error message is still the same :(

I saw on Google that people facing this issue are behind proxy, but that's not my case, I don't get it

**Comment by hydazz** [comment]
Manually downloading the files via the host rpi should work, cd to \<path to appdata\>/www/akaunting and delete any files that may be in that folder run the following:
```bash
curl -o \
   /tmp/akaunting.zip -L \
   "https://github.com/akaunting/akaunting/releases/download/2.1.11/Akaunting_2.1.11-Stable.zip"
```
```bash
unzip -q -o /tmp/akaunting.zip -d <path to appdata>/www/akaunting
```
```bash
chown abc:abc -R <path to appdata>/www/akaunting
```
```bash
rm /tmp/akaunting.zip
```
start the container and it should see the files there and start the webserver

**Comment by leomat** [comment]
Ok, that's a progress ! 
I don't have the github not found error anymore. 
But now, I have this one: 

![image](https://user-images.githubusercontent.com/227758/117305810-67c55f80-ae7f-11eb-85e9-2eaaad93b23c.png)

My mapping is correct: 

![image](https://user-images.githubusercontent.com/227758/117305261-dfdf5580-ae7e-11eb-9df6-090df2039221.png)

And in this folder, I have the cert file:
![image](https://user-images.githubusercontent.com/227758/117306031-9f340c00-ae7f-11eb-95c4-a5fc02e6bf60.png)

If I make a docker exec to check in the docker container, i also have the cert file in the '/config/keys' folder

I think we are getting closer !

**Comment by hydazz** [comment]
try delete the keys folder and restart the container

**Comment by leomat** [comment]
Thanks for you help. It's working. At least, for the Akaunting app. 
I have some issues with the database connection, but I guess it's on my side now. 

Maybe do you have a stack with mysql integration for Akaunting on a PI 4? If not, that's okay, I have some time to figure it out :) 

Thanks again for you help !

**Comment by hydazz** [comment]
what issues are you having with setting up the database?

**Comment by leomat** [comment]
Sorry for the delay. 
I've investigated a lot yesterday, and I solved my problem with the database (I got "InnoDB unknown storage engine", so I change in the source to MyISAM temporarily for the test...). 

It's working fine now, thanks for your help !
