### ISSUE TITLE
Update Akaunting

### ISSUE THREAD

**Issue by strzelba** [hydazz/docker-akaunting#3]
Hello, 
When i try to upload the update i get an error:
root@Akaunting:/config/www/akaunting# php artisan update:all
Starting update...
Updating core...
The command php artisan update core 1 failed.<br /><br />Exit Code: 1(General error)<br /><br />Working directory: /config/www/akaunting<br /><br />Output:<br />================<br />Not able to get the latest version of core!<br /><br /><br />Error Output:<br />================<br />
Not able to update core!
 
or,

root@Akaunting:/# cd config/www/akaunting/
root@Akaunting:/config/www/akaunting# php artisan update core 1
Not able to get the latest version of core!

What is wrong ?

**Comment by hydazz** [comment]
Try `s6-setuidgid abc php7 artisan update:all` In /config/www/akaunting

**Comment by strzelba** [comment]
Unfortunately, the same error.

**Comment by hydazz** [comment]
have you tried updating via the web interface?

**Comment by strzelba** [comment]
The update process stopped at 60%. I waited about 10 minutes and refresh the page. At the moment it shows the latest version, but I wonder if it should be so?

**Comment by hydazz** [comment]
If no updates are shown when you check for updates i would assume you would be on the latest version
